import assert from 'node:assert/strict'
import { modules } from '../src/modules.js'

const byId = Object.fromEntries(modules.map(module => [module.id, module]))
const choose = (n, r) => Array.from({ length: r }, (_, i) => (n - i) / (i + 1)).reduce((a, b) => a * b, 1)
const practice = (moduleId, questionId) => byId[moduleId].practice.find(q => q.id === questionId)
const approx = (actual, expected) => assert.ok(Math.abs(actual - expected) < 1e-9, `${actual} ≠ ${expected}`)

assert.equal((choose(4, 2) * choose(6, 1)) / (choose(10, 3) - choose(6, 3)), 9 / 25)
assert.equal(byId.probability.example.answer, '9/25')
assert.equal(64 - 4 * (17 - 1), 0)
assert.equal(byId.tangency.example.answer, '17')
assert.equal((72 / 360) * 25, 5)
assert.equal(byId.circles.example.answer, '5π')
assert.equal(135 / 60, 1.5 ** 2)
assert.equal(60 / 1.5, 40)
assert.equal(byId.exponential.example.answer, '40')
approx(125 * Math.sqrt(294 / 150) ** 3, 343)
assert.equal(byId.similarity.example.answer, '343')
const intersectionXs = [-3, 0, 3].filter(x => x * x + (x * x - 5) ** 2 === 25)
assert.equal(intersectionXs.length, 3)
assert.equal(byId['nonlinear-systems'].example.answer, '3')
assert.equal(-6 + -24, -30)
assert.equal(byId.linear.example.answer, '-30')
approx((.56 - .04) * 8000, 4160)
approx((.56 + .04) * 8000, 4800)
assert.ok(byId.statistics.example.answer.includes('4,160 to 4,800'))
assert.equal((-5 + 1) / (-5 - 2), 12 / ((-5) ** 2 - 4))
assert.equal(byId.rational.example.answer, '−5 only')

assert.equal(4 * 3 * 10, Number(practice('probability', 'p3').answer))
assert.equal(practice('tangency', 't3').answer, '−3 and 9')
assert.equal(practice('circles', 'c3').answer, '2π/3')
approx(27 * (5 / 3) ** 3, Number(practice('exponential', 'e2').answer))
approx(64 * (3 / 2) ** 3, Number(practice('similarity', 's2').answer))
assert.equal(practice('nonlinear-systems', 'n2').answer, '-25')
assert.equal(practice('linear', 'l2').answer, '-5/2')
assert.equal((.48 + .03) * 4000, Number(practice('statistics', 'st2').answer))
assert.equal(practice('rational', 'r2').answer, '-4')
console.log('Independent calculation audit passed for all 9 exemplars and selected higher-risk practice items.')
