// Original practice items. The four field-test items are excluded from the raw score.
const Q = (domain, difficulty, type, prompt, answer, options, steps, extra = {}) => ({ domain, difficulty, type, prompt, answer, options, steps, ...extra })
const answerOrder = [2,0,3,1, 1,3,0,2, 0,2,1,3, 3,1,2,0, 1,0,3,2, 2,3,1,0, 3,2,0,1, 0,1,2,3, 0]
let mcqIndex = 0

export const examModules = [
  [
    Q('Algebra', 'Easy', 'mcq', 'If 3(2x − 5) = 27, what is the value of x?', '7', ['5', '6', '7', '9'], ['Distribute: 6x − 15 = 27.', 'Add 15 and divide by 6: x = 7.']),
    Q('Problem Solving and Data Analysis', 'Easy', 'mcq', 'A store sold 80 notebooks on Monday and 100 on Tuesday. The number sold increased by what percent?', '25%', ['20%', '25%', '80%', '125%'], ['The increase is 100 − 80 = 20.', 'Use the original amount as the base: 20/80 = 0.25 = 25%.'], { context: true }),
    Q('Advanced Math', 'Easy', 'mcq', 'For the function f(x) = x² − 3x + 2, what is f(−2)?', '12', ['0', '4', '8', '12'], ['Substitute −2 for x.', 'f(−2) = (−2)² − 3(−2) + 2 = 4 + 6 + 2 = 12.']),
    Q('Geometry and Trigonometry', 'Easy', 'spr', 'A circle has radius 5. Its circumference is kπ. What is the value of k?', '10', null, ['Use C = 2πr.', 'C = 2π(5) = 10π, so k = 10.']),
    Q('Algebra', 'Medium', 'mcq', 'What is the slope of the line through (−2, 7) and (4, −5)?', '−2', ['−3', '−2', '1/2', '2'], ['Slope = change in y / change in x.', '(−5 − 7)/(4 − (−2)) = −12/6 = −2.'], { desmos: 'Plot the two points and use y₁ ~ mx₁ + b in a table.' }),
    Q('Problem Solving and Data Analysis', 'Medium', 'mcq', 'The table shows the number of books read by 10 students. What is the mean number of books?', '3.8', ['3.2', '3.5', '3.8', '4.0'], ['Multiply each value by its frequency: 2(3) + 4(5) + 6(2) = 38.', 'Divide by the 10 students: 38/10 = 3.8.'], { table: { headers: ['Books', 'Students'], rows: [['2', '3'], ['4', '5'], ['6', '2']] }, context: true }),
    Q('Advanced Math', 'Medium', 'mcq', 'The number of bacteria in a culture is modeled by B(t) = 240(1.15)^t, where t is hours after observation began. What does 240 represent?', 'The initial number of bacteria', ['The hourly increase in bacteria', 'The initial number of bacteria', 'The number after 1 hour', 'The percent increase each hour'], ['Set t = 0.', 'Since (1.15)^0 = 1, B(0) = 240.'], { context: true }),
    Q('Geometry and Trigonometry', 'Medium', 'spr', 'Two similar figures have corresponding side lengths in the ratio 3:5. The smaller figure has area 27 square units. What is the area of the larger figure?', '75', null, ['Area scales by the square of the side-length ratio.', 'Larger area = 27(5/3)² = 27(25/9) = 75.']),
    Q('Algebra', 'Medium', 'mcq', 'How many solutions does the system y = 2x + 3 and y = 2x − 4 have?', 'Zero', ['Zero', 'One', 'Two', 'Infinitely many'], ['Both lines have slope 2.', 'Their y-intercepts differ, so the parallel lines never intersect.'], { unscored: true }),
    Q('Algebra', 'Hard', 'mcq', 'A printing service charges a fixed setup fee plus a constant price per poster. An order of 40 posters costs $164, and an order of 65 posters costs $239. How much would an order of 100 posters cost?', '$344', ['$314', '$329', '$344', '$364'], ['The price per poster is (239 − 164)/(65 − 40) = 3 dollars.', 'The setup fee is 164 − 3(40) = 44 dollars.', 'For 100 posters, the cost is 44 + 3(100) = $344.'], { context: true }),
    Q('Advanced Math', 'Hard', 'mcq', 'The line y = 2x − 1 is tangent to the parabola y = x² − 6x + k. What is k?', '15', ['7', '15', '16', '17'], ['Set the two expressions for y equal: x² − 8x + (k + 1) = 0.', 'Tangency means one real intersection, so the discriminant is zero.', '64 − 4(k + 1) = 0, giving k = 15.'], { desmos: 'Graph y = x² − 6x + k and y = 2x − 1; add a slider for k and find the single touch.' }),
    Q('Problem Solving and Data Analysis', 'Hard', 'spr', 'A volunteer program has 90 juniors and 110 seniors. Of the juniors, 36 completed safety training; of the seniors, 66 completed it. If one trained volunteer is selected at random, what is the probability that the volunteer is a senior? Enter a fraction or decimal.', '11/17', null, ['The condition is that the volunteer is trained, so only trained volunteers belong in the denominator.', 'There are 36 + 66 = 102 trained volunteers, and 66 are seniors.', 'P(senior | trained) = 66/102 = 11/17.'], { context: true, table: { headers: ['Year', 'Trained', 'Not trained'], rows: [['Junior', '36', '54'], ['Senior', '66', '44']] } }),
    Q('Algebra', 'Hard', 'mcq', 'At a theater, adult tickets cost $14 and student tickets cost $9. A total of 84 tickets brought in $926. How many adult tickets were sold?', '34', ['26', '30', '34', '50'], ['Let a be the number of adult tickets. Then student tickets = 84 − a.', '14a + 9(84 − a) = 926.', '5a = 170, so a = 34.'], { context: true }),
    Q('Advanced Math', 'Hard', 'mcq', 'The quadratic function f(x) = a(x − 2)(x + 4) satisfies f(0) = 24. What is f(3)?', '−21', ['−21', '−14', '14', '21'], ['From f(0) = a(−2)(4) = 24, find a = −3.', 'Then f(3) = −3(1)(7) = −21.']),
    Q('Geometry and Trigonometry', 'Hard', 'mcq', 'The equation x² + y² − 8x + 6y = 0 represents a circle. What is its area?', '25π', ['5π', '16π', '25π', '49π'], ['Complete the square: (x − 4)² + (y + 3)² = 25.', 'The radius is 5, so the area is π(5)² = 25π.'], { desmos: 'Graph the equation to read its center and radius, then calculate area.' }),
    Q('Algebra', 'Hard', 'mcq', 'For what value of k are the lines 6x + ky = 12 and 4x − 2y = 7 parallel?', '−3', ['−12', '−3', '3', '12'], ['The second line has slope 2.', 'The first line has slope −6/k.', 'Set −6/k = 2 to get k = −3; the lines have different intercepts.']),
    Q('Advanced Math', 'Hard', 'spr', 'For positive k, the equation x² − (k + 5)x + 9 = 0 has exactly one real solution. What is k?', '1', null, ['Exactly one real solution means the discriminant equals zero: (k + 5)² − 36 = 0.', 'Thus k + 5 = 6 or k + 5 = −6, giving k = 1 or k = −11.', 'Since k is positive, k = 1.'], { desmos: 'Graph y = x² − (k + 5)x + 9 with a positive slider k; find when the parabola touches the x-axis.' }),
    Q('Problem Solving and Data Analysis', 'Hard', 'mcq', 'A researcher recruits 400 volunteers from one city and randomly assigns half to receive a new tutoring program and half to receive the usual program. Students in the new program show higher average scores. Which conclusion is best supported?', 'The program may have caused the increase for the volunteers, but the result cannot automatically be generalized to all students', ['The program caused an increase for every student in the city', 'The program may have caused the increase for the volunteers, but the result cannot automatically be generalized to all students', 'The program is associated with scores, but random assignment cannot support a causal conclusion', 'The result proves students in every city would benefit equally'], ['Random assignment supports a cause-and-effect comparison within the participating volunteers.', 'Because the volunteers were not randomly sampled from all students, broad population generalization is not justified.'], { context: true }),
    Q('Advanced Math', 'Hard', 'mcq', 'For what value of x does 4·3^x = 108·(1/3)^x?', '3/2', ['1/2', '1', '3/2', '3'], ['Rewrite (1/3)^x as 3^(−x), then divide by 4.', '3^x = 27·3^(−x), so 3^(2x) = 3³.', 'Therefore 2x = 3 and x = 3/2.'], { desmos: 'Graph y = 4·3^x and y = 108(1/3)^x; inspect the intersection x-coordinate.' }),
    Q('Algebra', 'Hard', 'mcq', 'A club has a budget of $75. A monthly service fee is $18, and each ticket costs $4. What is the greatest whole number of tickets the club can buy without exceeding its budget?', '14', ['13', '14', '15', '18'], ['Write 18 + 4t ≤ 75.', 'Then t ≤ 57/4 = 14.25.', 'Since t is a whole number, its greatest possible value is 14.'], { context: true }),
    Q('Advanced Math', 'Hard', 'spr', 'For x ≠ 4, the equation (x² − 16)/(x − 4) = x² − 5x + 12 holds for what value of x?', '2', null, ['Factor the numerator and cancel x − 4, while keeping the restriction x ≠ 4. The equation becomes x + 4 = x² − 5x + 12.', 'Rearrange: x² − 6x + 8 = (x − 2)(x − 4) = 0.', 'The candidate x = 4 is excluded because the original denominator is zero there. The valid solution is x = 2.']),
    Q('Algebra', 'Hard', 'mcq', 'For what value of k does the system kx + 5y = 20 and 6x + 10y = 40 have infinitely many solutions?', '3', ['2', '3', '5', '6'], ['Divide the second equation by 2 to get 3x + 5y = 20.', 'The first equation must match it exactly, so k = 3.'], { unscored: true })
  ],
  [
    Q('Algebra', 'Easy', 'mcq', 'If y = −3x + 8, what is y when x = 2?', '2', ['−2', '0', '2', '6'], ['Substitute x = 2.', 'y = −3(2) + 8 = 2.']),
    Q('Advanced Math', 'Easy', 'mcq', 'What is the solution to 2^x = 32?', '5', ['4', '5', '16', '30'], ['Rewrite 32 as 2⁵.', 'The bases match, so x = 5.']),
    Q('Geometry and Trigonometry', 'Medium', 'spr', 'A right triangle has legs of length 9 and 12. What is the sine of the acute angle opposite the shorter leg? Enter a fraction or decimal.', '3/5', null, ['The hypotenuse is √(9² + 12²) = √225 = 15.', 'Sine = opposite/hypotenuse = 9/15 = 3/5.'], { figure: 'triangle' }),
    Q('Problem Solving and Data Analysis', 'Medium', 'mcq', 'A survey of 600 randomly selected city residents found that 42% support a proposal. Which statement is the best conclusion?', 'About 42% of all city residents may support the proposal', ['Exactly 42% of all city residents support the proposal', 'About 42% of all city residents may support the proposal', 'The proposal will pass with 42% of votes', 'The survey proves the proposal caused support'], ['A random sample supports an estimate for the city population.', 'Sampling variation prevents an exact claim, and the survey does not establish votes or causation.'], { context: true }),
    Q('Algebra', 'Hard', 'mcq', 'The system 3x + 2y = 22 and 5x − 2y = 10 has solution (x, y). What is x² − y?', '11', ['9', '11', '13', '21'], ['Add the equations: 8x = 32, so x = 4.', 'Then 3(4) + 2y = 22, so y = 5.', 'x² − y = 16 − 5 = 11.']),
    Q('Advanced Math', 'Hard', 'mcq', 'The expression x² + bx + 12 has x − 3 as a factor. What is its other linear factor?', 'x − 4', ['x + 4', 'x − 4', 'x + 7', 'x − 7'], ['Because x − 3 is a factor, x = 3 is a root.', '9 + 3b + 12 = 0 gives b = −7.', 'x² − 7x + 12 = (x − 3)(x − 4).']),
    Q('Geometry and Trigonometry', 'Hard', 'spr', 'A sector of a circle has radius 10 and central angle 72°. Its area is kπ square units. What is k?', '20', null, ['A 72° sector is 72/360 = 1/5 of the circle.', 'Sector area = (1/5)π(10)² = 20π.'], { figure: 'sector' }),
    Q('Algebra', 'Hard', 'mcq', 'A line passes through (6, 1) and is perpendicular to the line through (1, −4) and (5, 2). What is the y-intercept of the first line?', '5', ['−5', '−3', '3', '5'], ['The given line has slope (2 − (−4))/(5 − 1) = 3/2.', 'A perpendicular line has slope −2/3.', 'Use 1 = (−2/3)(6) + b, giving b = 5.']),
    Q('Advanced Math', 'Hard', 'mcq', 'What is the solution to √(x + 10) = x − 2?', '6', ['−1', '2', '6', '9'], ['The right side must be nonnegative, so x ≥ 2.', 'Squaring gives x + 10 = (x − 2)², or x² − 5x − 6 = 0.', 'The candidates are 6 and −1; only 6 satisfies the original equation.']),
    Q('Problem Solving and Data Analysis', 'Hard', 'mcq', 'The number of animals in a wildlife preserve is modeled by P(t) = ab^t, where t is years after the first count. The table shows three counts. According to the model, what is P(4), to the nearest whole animal?', '253', ['225', '253', '338', '400'], ['At t = 0, a = 800.', 'The common ratio is b = 600/800 = 0.75; the third row confirms 600(0.75) = 450.', 'P(4) = 800(0.75)^4 = 253.125, which rounds to 253.'], { context: true, unscored: true, table: { headers: ['t', 'P(t)'], rows: [['0', '800'], ['1', '600'], ['2', '450']] } }),
    Q('Advanced Math', 'Hard', 'spr', 'What is x if 5·2^(x + 1) = 80?', '3', null, ['Divide by 5: 2^(x + 1) = 16 = 2⁴.', 'Thus x + 1 = 4 and x = 3.']),
    Q('Algebra', 'Hard', 'mcq', 'For what value of k does the equation (k − 2)x + 6 = 4x + 9 have no solution?', '6', ['2', '4', '6', '9'], ['A linear equation has no solution when the x-coefficients match but constants differ.', 'Set k − 2 = 4, so k = 6. Then 4x + 6 = 4x + 9 is impossible.']),
    Q('Geometry and Trigonometry', 'Hard', 'mcq', 'A cylinder is redesigned so that its radius is tripled and its height is doubled. The new volume is how many times the original volume?', '18', ['6', '9', '12', '18'], ['Cylinder volume is πr²h.', 'Tripling r multiplies volume by 3² = 9; doubling h multiplies by 2.', 'The total factor is 9(2) = 18.'], { context: true }),
    Q('Advanced Math', 'Hard', 'mcq', 'The line tangent to y = x² − 6x + 13 at x = 2 passes through which point?', '(0, 9)', ['(0, 1)', '(0, 5)', '(0, 9)', '(0, 13)'], ['At x = 2, the parabola has y = 5. Write the tangent line as y = mx + b, so 2m + b = 5.', 'Setting the line equal to the parabola gives x² − (6 + m)x + (13 − b) = 0. A single touch at x = 2 means this quadratic equals (x − 2)².', 'Compare x-coefficients: −6 − m = −4, so m = −2. Then b = 9, and the line passes through (0, 9).'], { desmos: 'Graph the parabola and candidate lines; the tangent has exactly one intersection near x = 2.' }),
    Q('Algebra', 'Hard', 'spr', 'A tank starts with 84 liters. One pipe adds 18 liters per minute while its drain removes 6 liters per minute. A second tank starts with 300 liters and loses 6 liters per minute. After how many minutes will both tanks contain the same amount?', '12', null, ['The first tank changes at a net rate of 18 − 6 = 12 liters per minute: A(t) = 84 + 12t.', 'The second tank has B(t) = 300 − 6t. Set the amounts equal.', '84 + 12t = 300 − 6t, so 18t = 216 and t = 12.'], { context: true }),
    Q('Advanced Math', 'Hard', 'mcq', 'For the function f(x) = (3x² − 12)/(x² − 4), which statement describes its graph?', 'It is the line y = 3 with holes at x = −2 and x = 2', ['It has vertical asymptotes at x = −2 and x = 2', 'It is the line y = 3 with holes at x = −2 and x = 2', 'It is the line y = 3 for every real x', 'It has a horizontal asymptote at y = −3'], ['Factor: (3x² − 12)/(x² − 4) = 3(x² − 4)/(x² − 4) = 3 where x² − 4 ≠ 0.', 'The original denominator is zero at x = −2 and x = 2, so those inputs remain excluded.', 'The graph is the horizontal line y = 3 with a hole at each excluded x-value.']),
    Q('Algebra', 'Hard', 'mcq', 'A linear function f satisfies f(2) = 11 and f(8) = 35. A linear function g satisfies g(1) = 7 and its graph is perpendicular to the graph of f. At what x-value do the graphs intersect?', '1', ['−1', '0', '1', '2'], ['The slope of f is (35 − 11)/(8 − 2) = 4, so f(x) = 4x + 3.', 'The slope of g is −1/4. Since g(1) = 7, g(x) = −x/4 + 29/4.', 'Set 4x + 3 = −x/4 + 29/4. Multiplying by 4 gives 16x + 12 = −x + 29, so x = 1.']),
    Q('Advanced Math', 'Advanced', 'mcq', 'For what value of k does the system y = x² − 4x + k and y = 2x + 7 have exactly one real solution?', '16', ['7', '9', '16', '18'], ['Equate the expressions: x² − 6x + (k − 7) = 0.', 'One real solution requires discriminant 36 − 4(k − 7) = 0.', 'Solve 36 − 4k + 28 = 0 to get k = 16.'], { unscored: true }),
    Q('Geometry and Trigonometry', 'Advanced', 'spr', 'The circle x² + y² − 12x + 8y + c = 0 is tangent to the x-axis. What is c?', '36', null, ['Complete the square: (x − 6)² + (y + 4)² = 52 − c.', 'The center is (6, −4), so tangency to the x-axis requires radius 4.', 'Set 52 − c = 4² = 16, giving c = 36.'], { desmos: 'Graph the circle with a slider for c and find the value at which it just touches y = 0.' }),
    Q('Advanced Math', 'Advanced', 'mcq', 'For an exponential function f(x) = ab^x, where a and b are positive, f(1) = 18 and f(4) = 486. What is f(−2)?', '2/3', ['2/3', '2', '6', '18'], ['Divide f(4) by f(1): b³ = 486/18 = 27, so b = 3.', 'Then ab = 18 gives a = 6.', 'Use the negative exponent: f(−2) = 6(3)^(−2) = 6/9 = 2/3.']),
    Q('Algebra', 'Advanced', 'mcq', 'The line 3x − 2y = 7 is parallel to the line (k + 1)x + (k − 2)y = 11. What is k?', '4/5', ['2/5', '4/5', '5/4', '8'], ['For parallel lines, the ratios of corresponding x- and y-coefficients match: (k + 1)/3 = (k − 2)/(−2).', 'Cross-multiply: −2(k + 1) = 3(k − 2), so 5k = 4 and k = 4/5.', 'At this value, the constants are not in the same ratio, so the lines are distinct.']),
    Q('Problem Solving and Data Analysis', 'Advanced', 'spr', 'Of 240 students, 60 study both French and Spanish, and 48 study neither language. Among students who study exactly one of the languages, twice as many study only Spanish as study only French. How many students study Spanish?', '148', null, ['The number studying at least one language is 240 − 48 = 192.', 'Exactly one language: 192 − 60 = 132. Split this in a 1:2 ratio, giving 44 French-only and 88 Spanish-only.', 'Spanish students = 88 + 60 = 148.'], { context: true })
  ]
].map((items, moduleIndex) => items.map((item, position) => {
  if (item.type === 'mcq') {
    const current = item.options.indexOf(item.answer)
    const target = answerOrder[mcqIndex++]
    const shift = (target - current + 4) % 4
    item.options = item.options.map((_, index) => item.options[(index - shift + 4) % 4])
  }
  return { ...item, id: `M${moduleIndex + 1}Q${String(position + 1).padStart(2, '0')}`, module: moduleIndex + 1, position: position + 1 }
}))

export const allExamQuestions = examModules.flat()

export function numericResponse(input) {
  const cleaned = String(input ?? '').trim().replace(/−/g, '-').replace(/,/g, '')
  const fraction = cleaned.match(/^([+-]?\d+)\/([+-]?\d+)$/)
  if (fraction) return Number(fraction[2]) === 0 ? NaN : Number(fraction[1]) / Number(fraction[2])
  return /^[+-]?(?:\d+\.?\d*|\.\d+)$/.test(cleaned) ? Number(cleaned) : NaN
}

export function isCorrect(question, response) {
  if (question.type === 'mcq') return response === question.answer
  const actual = numericResponse(response)
  const expected = numericResponse(question.answer)
  return Number.isFinite(actual) && Number.isFinite(expected) && Math.abs(actual - expected) < 1e-8
}
